project_id = "tcvtgzubarrsppppazfo"

[functions.fetch-verse-of-the-day]
verify_jwt = false

[functions.bible-proxy]
verify_jwt = false

[functions.studio-ai-assistant]
verify_jwt = false

[functions.studio-transcribe]
verify_jwt = false
